spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jscode-springboot?serverTimezone=UTC&characterEncoding=UTF-8
    username: hoseok
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect